### ISSUE TITLE
Should not read from file

### ISSUE THREAD

**Issue by mmaftea** [ssg2655/MARK#1]
**The application i asked to be designed migth not been fully understood by you.**
For now i want you to refactor the code because for now we do not need to read from a file.
The final result i was waiting for was :
![Screenshot 2024-02-17 181920](https://github.com/ssg2655/MARK/assets/160339068/f6b1aee0-8334-471b-b946-5185cc86ff19)
Try to make it so it would work like this also u need to add the minute when somebody scored 
Also u have no players . Thats no fun ! 
Thats not really oop what u made so try to make the output as close to the image and later ill give you further instructions!

**Comment by mmaftea** [comment]
Ps. Add these entities to make it more oop designed.
**Also do not use ids!!!!!!**
Player Class
Each player has a name.
Team Class
Each team has a name. A team also contains a roster of its players.
Goal Class
The application must keep track of goals scored. A goal can be described by the team who scored it, the player who scored it, and the time it was scored. Represent time as a double.
Game Class
The application must keep track of games played. A game can be described by its home team, its away team, and each goal that may have been scored.
League Class
This class contains a single main method. The main method simulates the league by instantiating objects and assigning values.
Instantiate and name at least six players and two teams. To remember which players play for which team, you may find it helpful to have player names and their team names start with the same letter.

**Comment by ssg2655** [comment]
im sorry JEFE, i will remake the code, please dont kill me, im a good worker, i can work harder

**Comment by ssg2655** [comment]
Hi Mark,

I've remade the code, sadly, but I don't know how to implement double-level sorting with maps. Also, doing it with lists was challenging. Additionally, I didn't create a Leaderboard class as I thought it's useless.
