### ISSUE TITLE
Should use a good structure

### ISSUE THREAD

**Issue by mmaftea** [ssg2655/MARK#2]
![image](https://github.com/ssg2655/MARK/assets/160339068/e85081b6-baf5-4c3a-a019-41d2c24b727a)
Do i even need to say anything.
Like what is this structure why are there 2 src folders???
And why u have duplicated classes.
And also why u keep the old code around delete it.
Make it better so we could continue.
This is unrunnable.

**Comment by ssg2655** [comment]
NAH BRO

**Comment by ssg2655** [comment]
ok, i've deleted the old code

**Comment by ssg2655** [comment]
i was just a mistake of uploading, im so sorry
