### ISSUE TITLE
Should work as intended

### ISSUE THREAD

**Issue by mmaftea** [ssg2655/MARK#3]
Well ok let me break down this for u
Look at what ive told u to redo .
And think how to do what i meant of for u to do
At first read the teams and their players
then generate a couple games like these random
![image](https://github.com/ssg2655/MARK/assets/160339068/e3cf66a8-c242-4332-95fa-382db984f6a1)
and make the stats in league class like these for now it should work with only two teams.
![image](https://github.com/ssg2655/MARK/assets/160339068/94afdf82-c0e6-46fa-b7b4-9fe01a2ff24d)

Fix this

**Comment by ssg2655** [comment]
ok
